/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-113412-g0b8e51b584-20240124"
#endif /* AVUTIL_FFVERSION_H */
